spring.application.name=baitap3_spring_mongodb_api_thymeleaf

server.port=8081

# K\u1EBFt n\u1ED1i \u0111\u01B0\u1EDDng d\u1EABn Server MongoDB ng\u1EA7m \u0111\u1EBFn \u1ED5 D:
spring.mongodb.uri=mongodb://localhost:27017/huu_loc_movie_project

# Khai b\u00E1o s\u1ED1 items/page
app.movies.page-size=5