spring.application.name=baitap4_spring_mongodb_thymeleaf_import

# C\u00E0i \u0111\u1EB7t c\u1ED5ng k\u1EBFt n\u1ED1i
server.port=8082

# K\u1EBFt n\u1ED1i \u0111\u01B0\u1EDDng d\u1EABn Server MongoDB ng\u1EA7m \u0111\u1EBFn c\u01A1 s\u1EDF d\u1EEF li\u1EC7u t\u1EA1i \u1ED5 c\u1EE9ng
spring.mongodb.uri=mongodb://localhost:27017/huu_loc_restaurant_project

# Gi\u1EDBi h\u1EA1n t\u1ED1i \u0111a cho m\u1ED9t t\u1EC7p tin \u0111\u01A1n l\u1EBB khi \u0111\u1EA9y qua card m\u1EA1ng
spring.servlet.multipart.max-file-size=20MB

# Gi\u1EDBi h\u1EA1n t\u1ED5ng dung l\u01B0\u1EE3ng c\u1EE7a to\u00E0n b\u1ED9 request HTTP (bao g\u1ED3m file + c\u00E1c d\u1EEF li\u1EC7u text \u0111i k\u00E8m),
# gi\u00FAp ch\u1EB7n \u0111\u1EE9ng ho\u00E0n to\u00E0n l\u1ED7i v\u1EE1 tr\u1EADn ngo\u1EA1i l\u1EC7 MaxUploadSizeExceededException c\u1EE7a Server Tomcat
# nh\u00FAng khi n\u1EA1p file d\u1EEF li\u1EC7u qu\u00E1 l\u1EDBn
spring.servlet.multipart.max-request-size=20MB

# \u0110\u1ED3ng b\u1ED9 h\u1EB1ng s\u1ED1 c\u1EA5u h\u00ECnh ph\u00E2n trang h\u1EC7 th\u1ED1ng (10 nh\u00E0 h\u00E0ng tr\u00EAn 1 trang)
app.restaurants.page-size=10
