spring.application.name=baitap8_api

# Gi\u1EDBi h\u1EA1n k\u00EDch th\u01B0\u1EDBc file Forn upload
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=5MB

# Th\u01B0 m\u1EE5c c\u0103n c\u1EE9 l\u01B0u file ngo\u00E0i \u1EDF \u0111\u0129a D:
app.upload.dir=D:/JV2_intelliJ/baitap8_externalFiles

# C\u1EA5u h\u00ECnh s\u1ED1 l\u01B0\u1EE3ng d\u00F2ng hi\u1EC3n th\u1ECB t\u1ED1i \u0111a trong 1 trang Web Users
app.users.page-size=5

